/** Declared raw and advisory metric ids emitted by native duplication analysis. */
export const DUPLICATION_METRICS = [
	"duplication.candidate.covered-lines.production",
	"duplication.candidate.covered-lines.test",
	"duplication.candidate.density.production",
	"duplication.candidate.density.test",
	"duplication.candidate.eligible-lines.production",
	"duplication.candidate.eligible-lines.test",
	"duplication.candidate.equality-preserving-groups.production",
	"duplication.candidate.equality-preserving-groups.test",
	"duplication.candidate.exact-data-groups.production",
	"duplication.candidate.exact-data-groups.test",
	"duplication.candidate.executable-groups.production",
	"duplication.candidate.executable-groups.test",
	"duplication.candidate.independent-copies.production",
	"duplication.candidate.independent-copies.test",
	"duplication.candidate.kind-preserving-groups.production",
	"duplication.candidate.kind-preserving-groups.test",
	"duplication.candidate.statement-aligned-groups.production",
	"duplication.candidate.statement-aligned-groups.test",
	"duplication.density.production",
	"duplication.density.test",
	"duplication.duplicated-lines.production",
	"duplication.duplicated-lines.test",
	"duplication.groups.production",
	"duplication.groups.test",
] as const;
